version: '3'

services:
  # frontend:
  #   container_name: frontend
  #   image: stevechapman/legal_nlp:1.7
  #   command: ["streamlit", "run", "frontend/\U0001F3E0Home.py"]
  #   working_dir: /src/legal_nlp
  #   environment:
  #     - NLP_API_CONNECTION_STRING=http://backend:8542/
  #   ports:
  #     - "8501:8501"
  #   networks:
  #     - app-network

  # backend:
  #   container_name: backend
  #   image: stevechapman/legal_nlp:1.7
  #   command: ["uvicorn", "launch:app", "--host=0.0.0.0", "--port=8542"]
  #   working_dir: /src/legal_nlp/backend
  #   environment:
  #     - HUGGING_FACE_HUB_TOKEN=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
  #   ports:
  #     - "8542:8542"
  #   networks:
  #     - app-network

  both:
    container_name: both
    image: stevechapman/legal_nlp:1.9
    command: ["python", "start_both.py"]
    working_dir: /src/legal_nlp
    environment:
      - NLP_API_CONNECTION_STRING=http://0.0.0.0:8542/
      - HUGGING_FACE_HUB_TOKEN=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
    ports:
      - "8501:8501"
      - "8542:8542"
    networks:
      - app-network

  # simple-rest:
  #   container_name: simple-rest
  #   image: stevechapman/simple-rest:1.0
  #   command: ["python", "app.py"]
  #   working_dir: /
  #   ports:
  #     - "8544:8544"
  #   networks:
  #     - app-network     

networks:
  app-network:
    driver: bridge